In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
iris_flowers=load_iris()
from sklearn.model_selection import cross_val_score
import pandas as pd
import numpy as np

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris_flowers.data,iris_flowers.target,test_size=0.3)

Logistic Regression

In [24]:
scores_l=cross_val_score(LogisticRegression(),iris_flowers.data,iris_flowers.target)
scores_l

C:\Users\Dell\PYTHON\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [28]:
np.average(scores_l)

0.9733333333333334

Decision Tree

In [25]:
scores_d=cross_val_score(DecisionTreeClassifier(),iris_flowers.data,iris_flowers.target)
scores_d

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [29]:
np.average(scores_d)

0.9666666666666668

SVM

In [26]:
scores_svm=cross_val_score(SVC(),iris_flowers.data,iris_flowers.target)
scores_svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [30]:
np.average(scores_svm)

0.9666666666666666

Random Forest

In [27]:
scores_rf=cross_val_score(RandomForestClassifier(),iris_flowers.data,iris_flowers.target)
scores_rf

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [31]:
np.average(scores_rf)

0.96

### result:Logistic regression is best(97%)